[env]
_.file = '.env.json'

[tasks.dev]
run = [
       'clear',
       'go run actor-facade/main.go | fx'
]

[tasks.test]
run = [
       'clear',
       'dlv debug actor-facade/main.go'
]

[tools]
"go:github.com/nats-io/natscli/nats" = "latest"
