[env]
_.file = '.env.json'

[tasks.dev]
run = [
       'clear',
       'go run actor-facade/main.go | jq .'
]

[tasks.test]
run = [
       'clear',
       'dlv debug actor-facade/main.go'
]

[tools]
node = "22"
pnpm = "latest"

# [tools]
# "go:github.com/nats-io/natscli/nats" = "latest",
# "jq"
